#!/bin/sh

if [ -z "$API_KEY" ] || [ -z "$API_SECRET" ]
then
   export API_KEY=45531972
   export API_SECRET=f0845b25441e25952c16f7940cad4174fa92b47c
fi

if [ -d "storage" ]
then
  rm -rf storage/
fi

php -S 0.0.0.0:8080 -t web web/index.php
